sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - "12"
script:
  - npm run precommit
after_success:
  # Deploy code coverage report to codecov.io
  - npm run test:coverage:deploy
